/********************************************************************
	Created:	2013/01/17  19:11
	Filename: 	IniReader.cpp
	Author:		rrrfff
	Url:	    http://blog.csdn.net/rrrfff
*********************************************************************/
#include <RLib_Import.h>

using namespace System::Ini;

//-------------------------------------------------------------------------

int __stdcall WinMain(__in HINSTANCE /*hInstance*/, __in_opt HINSTANCE /*hPrevInstance*/,
					  __in LPSTR /*lpCmdLine*/, __in int /*nShowCmd*/)
{
	IniFile ini;
	ini.Items.Add(new IniComment()); // empty comment
	ini.Items.Add(new IniComment(_R(" This File has been generated by RLib")));
	ini.Items.Add(new IniComment(_R(" Copyright (c) 2016 rrrfff, rrrfff@foxmail.com")));   
	
	ini["Section"]["Key"] = _R("Value");
	ini.SaveFile(_T("Config.ini"), UTF8Encoding);

	return 0;
}