var namespace_system =
[
    [ "Collections", "d5/da7/namespace_system_1_1_collections.html", "d5/da7/namespace_system_1_1_collections" ],
    [ "Config", "da/d8b/namespace_system_1_1_config.html", "da/d8b/namespace_system_1_1_config" ],
    [ "IO", "dc/d30/namespace_system_1_1_i_o.html", "dc/d30/namespace_system_1_1_i_o" ],
    [ "Net", "d7/d5b/namespace_system_1_1_net.html", "d7/d5b/namespace_system_1_1_net" ],
    [ "Security", "d4/d8b/namespace_system_1_1_security.html", "d4/d8b/namespace_system_1_1_security" ],
    [ "Text", "d8/d71/namespace_system_1_1_text.html", "d8/d71/namespace_system_1_1_text" ],
    [ "Threading", "d3/d81/namespace_system_1_1_threading.html", "d3/d81/namespace_system_1_1_threading" ],
    [ "Xml", "d9/d2f/namespace_system_1_1_xml.html", "d9/d2f/namespace_system_1_1_xml" ],
    [ "AppBase", "da/d80/class_system_1_1_app_base.html", "da/d80/class_system_1_1_app_base" ],
    [ "AutoFinalize", "d3/d27/class_system_1_1_auto_finalize.html", "d3/d27/class_system_1_1_auto_finalize" ],
    [ "AutoRunOnce", "d6/dfc/class_system_1_1_auto_run_once.html", "d6/dfc/class_system_1_1_auto_run_once" ],
    [ "BigInt", "d1/dcf/class_system_1_1_big_int.html", "d1/dcf/class_system_1_1_big_int" ],
    [ "DateTime", "d8/dee/class_system_1_1_date_time.html", "d8/dee/class_system_1_1_date_time" ],
    [ "Double", "d7/d13/class_system_1_1_double.html", "d7/d13/class_system_1_1_double" ],
    [ "Exception", "d1/df8/class_system_1_1_exception.html", "d1/df8/class_system_1_1_exception" ],
    [ "Float", "d6/d45/class_system_1_1_float.html", "d6/d45/class_system_1_1_float" ],
    [ "GlobalizeString", "d9/dd8/class_system_1_1_globalize_string.html", "d9/dd8/class_system_1_1_globalize_string" ],
    [ "Int32", "d9/dbd/class_system_1_1_int32.html", "d9/dbd/class_system_1_1_int32" ],
    [ "IntegerVariant", "d0/dfa/class_system_1_1_integer_variant.html", "d0/dfa/class_system_1_1_integer_variant" ],
    [ "LocalObject", "dd/d1c/class_system_1_1_local_object.html", "dd/d1c/class_system_1_1_local_object" ],
    [ "Long", "d8/de4/class_system_1_1_long.html", "d8/de4/class_system_1_1_long" ],
    [ "ManagedMemoryBlock", "d5/d38/class_system_1_1_managed_memory_block.html", "d5/d38/class_system_1_1_managed_memory_block" ],
    [ "ManagedObject", "de/d9a/class_system_1_1_managed_object.html", "de/d9a/class_system_1_1_managed_object" ],
    [ "Object", "d5/df0/class_system_1_1_object.html", "d5/df0/class_system_1_1_object" ],
    [ "Random", "db/df8/class_system_1_1_random.html", null ],
    [ "SafeObject", "df/d3f/class_system_1_1_safe_object.html", "df/d3f/class_system_1_1_safe_object" ],
    [ "String", "db/d0b/class_system_1_1_string.html", "db/d0b/class_system_1_1_string" ],
    [ "StringArray", "d6/d4b/class_system_1_1_string_array.html", "d6/d4b/class_system_1_1_string_array" ],
    [ "Timer", "de/da9/class_system_1_1_timer.html", "de/da9/class_system_1_1_timer" ],
    [ "UInt32", "d9/d24/class_system_1_1_u_int32.html", "d9/d24/class_system_1_1_u_int32" ],
    [ "ULong", "d9/df0/class_system_1_1_u_long.html", "d9/df0/class_system_1_1_u_long" ],
    [ "Variant", "d5/d87/class_system_1_1_variant.html", "d5/d87/class_system_1_1_variant" ]
];