#define _DISABLE_FILE_REG
#define _DISABLE_TEXTSPEAKER
#define _DISABLE_REGEXP
#define _DISABLE_MAIL
#define _DISABLE_OBAMA64
#define _DISABLE_BIGINT
//#define _DISABLE_UAC
//#define _DISABLE_CRC
//#define _DISABLE_XML
//#define _DISABLE_TLS
//#define _DISABLE_AES
//#define _DISABLE_RSA
//#define _DISABLE_CIPHER
//#define _DISABLE_BASE64