var searchData=
[
  ['accesscontrol',['AccessControl',['../namespace_system_1_1_security_1_1_access_control.html',1,'System::Security']]],
  ['collections',['Collections',['../namespace_system_1_1_collections.html',1,'System']]],
  ['compression',['Compression',['../namespace_system_1_1_i_o_1_1_compression.html',1,'System::IO']]],
  ['cryptography',['Cryptography',['../namespace_system_1_1_security_1_1_cryptography.html',1,'System::Security']]],
  ['generic',['Generic',['../namespace_system_1_1_collections_1_1_generic.html',1,'System::Collections']]],
  ['hash',['Hash',['../namespace_system_1_1_generic_1_1_hash.html',1,'System::Generic']]],
  ['io',['IO',['../namespace_system_1_1_i_o.html',1,'System']]],
  ['microsoft',['Microsoft',['../namespace_system_1_1_microsoft.html',1,'System']]],
  ['net',['Net',['../namespace_system_1_1_net.html',1,'System']]],
  ['principal',['Principal',['../namespace_system_1_1_security_1_1_principal.html',1,'System::Security']]],
  ['runtime',['Runtime',['../namespace_system_1_1_runtime.html',1,'System']]],
  ['search',['Search',['../namespace_system_1_1_generic_1_1_search.html',1,'System::Generic']]],
  ['security',['Security',['../namespace_system_1_1_security.html',1,'System']]],
  ['serialization',['Serialization',['../namespace_system_1_1_runtime_1_1_serialization.html',1,'System::Runtime']]],
  ['sorting',['Sorting',['../namespace_system_1_1_generic_1_1_sorting.html',1,'System::Generic']]],
  ['standard',['Standard',['../namespace_system_1_1_standard.html',1,'System']]],
  ['system',['System',['../namespace_system.html',1,'']]],
  ['text',['Text',['../namespace_system_1_1_text.html',1,'System']]],
  ['threading',['Threading',['../namespace_system_1_1_threading.html',1,'System']]],
  ['xml',['Xml',['../namespace_system_1_1_xml.html',1,'System']]]
];
